#*******************************************************************************
# Copyright (c) Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
# which is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# SPDX-License-Identifier: (EPL-2.0 OR Apache-2.0)
#*******************************************************************************

name: CI Build

on:
  push:
    branches-ignore:
    - 'dependabot/**'
    paths-ignore:
    - 'docs/**'
    - '.github/**/*docs*'
    - '.github/**/*codeql*'
    - '.github/*.yml'
  pull_request:
    paths-ignore:
    - 'docs/**'
    - '.github/**/*docs*'
    - '.github/**/*codeql*'
    - '.github/*.yml'

env:
  LC_ALL: en_US.UTF-8
  MAVEN_OPTS: >-
    -Dhttp.keepAlive=false
    -Dmaven.wagon.http.pool=false
    -Dmaven.wagon.http.retryHandler.count=3

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
        - 'ubuntu-latest'
        java:
        - '8'
        - '11'
        include:
        - os: 'ubuntu-latest'
          java: '17'
          canonical: ${{ (github.repository == 'eclipse/transformer') && ((github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/release')) && (github.event_name != 'pull_request') }}
        - os: 'ubuntu-latest'
          java: '17'
          experimental: true
          mavenopts: '-Pbnd-snapshot'
        - os: 'windows-latest'
          java: '17'
    name: JDK${{ matrix.java }} ${{ matrix.os }} ${{ matrix.mavenopts }}
    runs-on: ${{ matrix.os }}
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604 # v2.5.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Git Checkout
      uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - name: Set up Java ${{ matrix.java }}
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build
      id: build
      continue-on-error: ${{ matrix.experimental }}
      run: |
        ./.github/scripts/build.sh ${{ matrix.mavenopts }}
    - name: Configure settings.xml for Publish
      if: ${{ matrix.canonical }}
      uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3.12.0
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_TOKEN
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: Publish
      if: ${{ matrix.canonical }}
      run: |
        ./.github/scripts/publish.sh -Possrh
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
